In [7]:
# import libraries
import numpy as np 

# what is an array ?

An array is a way to store and organize a group of things (like numbers, names or other data) so they can be easily accessed. 

In an array, each thing gets its own number called an "index." This number is used to quickly find that item in the array.

Arrays let you look up any item immediately by its index number, no matter how many things are in the array. 

You can put arrays inside of arrays to organize data in rows and columns too.

The items in an array must all be the same type of thing (like all numbers or all names). 

Arrays are helpful when you need to work with a big list of things and need to easily get, change or find items in it using their index numbers.

Many coding languages have arrays to help programmers easily organize and look up data in their programs.

In [8]:

np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [9]:
# assigning a variable
a = np.arange(6)                 # it is a 1d array 
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [ ]:
a2 = a[np.newaxis, :]           # 2d array because its shows 2 brackets , we gave a values of rows and column
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [ ]:
a3= a2[np.newaxis,:]               # 3d array
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

-----

## Why we do have !D,2D and 3D arrays and where we need then in data science?

----

### Creating arrays with NUMPY.

In [13]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3,4,5,6) , (5,6,7,8,9,10)])

In [14]:
type(a)     # type of array

numpy.ndarray

In [15]:
type(b)

numpy.ndarray

In [16]:
a.dtype     #type of array elements

dtype('int32')

In [17]:
b.dtype

dtype('int32')

In [18]:
a.shape
b.shape

(2, 6)

In [19]:
print(a)

[1 2 3 4 5 6]


In [20]:
print(b)
b.shape

[[ 1  2  3  4  5  6]
 [ 5  6  7  8  9 10]]


(2, 6)

## Initialize Array

In [21]:
zeros= np.zeros((3,4))  # np.zeros function is use only for showing zero values in array
zeros 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
ones= np.ones((4,5)) # that one function shows only one in the array
ones


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
full= np.full((5,7) , 9)        # here full funtion use for desired array
full

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [27]:
# Creating an IDENTITY MATRIX

identity= np.eye(3)         # give us a identity matrix that shows a value of 1 in diagnol form
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Attributes of array

In [28]:
a.shape         # give us the shape of array

(6,)

In [29]:
len(a)         # give us the length of array

6

In [30]:
b.ndim          # give us the diemensions

2

In [31]:
b.size          # total elements in array 

12

## Basics Operations

In [32]:
a

array([1, 2, 3, 4, 5, 6])

In [33]:
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  9, 10]])

### Subtraction

In [34]:
c = a-b
c

array([[ 0,  0,  0,  0,  0,  0],
       [-4, -4, -4, -4, -4, -4]])

In [35]:
c=b-a
c

array([[0, 0, 0, 0, 0, 0],
       [4, 4, 4, 4, 4, 4]])

### Addition

In [36]:
c = a+b
c

array([[ 2,  4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14, 16]])

In [37]:
# Nother way of addition
c = np.add(a,b)
c

array([[ 2,  4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14, 16]])

### Multiplication

In [38]:
c = a*b
c

array([[ 1,  4,  9, 16, 25, 36],
       [ 5, 12, 21, 32, 45, 60]])

### Division

In [39]:
c= a/b
c

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556,
        0.6       ]])

### Square root

In [40]:
c = a**2
c

array([ 1,  4,  9, 16, 25, 36])